### ISSUE TITLE
AgeCheck

### ISSUE THREAD

**Issue by Richie94** [Richie94/steamRecommend#1]
Gerade festgestellt, dass wenn man Daten über den Store crawlt auf nen Agecheck stoßen kann. Bei SteamDB ist das nicht der Fall. Muss man sehen ob man den irgendwie erkennen können will oder dann in den Einzelfällen steamdb anfragt?!

**Comment by Richie94** [comment]
Und auch dazu related aber weniger gut zu fixen: ab und zu hat der steam store die appIDs nicht vorhanden aber steamDB dafür. einfach weglassen oder wie machen wir das dann?

**Comment by Luux** [comment]
In diesem Fall wird das Spiel wahrscheinlich nicht mehr über Steam verkauft. Da bei so was das Game natürlich trotzdem für die Besitzer verfügbar bleibt, verschwindet der Eintrag in der SteamDB auch nicht...

**Comment by Richie94** [comment]
Hm okay ich denke wir cutten die dann einfach raus...

**Comment by Luux** [comment]
Das ist dann aber evtl. auch nicht sinnvoll, da die Spiele in einigen Bibliotheken auftauchen werden. Vielleicht ein weiteres Flag, das anzeigt, ob das Spiel noch vertrieben wird? 

Darunter sollten auch z.B. Beta-Versionen oder ähnliches fallen. Alle Spiele bzw. Software halt, die zwar auf Steam sind, aber keinen Steam-Eintrag haben (noch nicht oder nicht mehr)

**Comment by Richie94** [comment]
hm okay dann sammeln wir die erstmal trotzdem und sehen dann später ob wir dafür vlt ausnahmen oder so beim lernen erstellen... oder alternativ die aus anderen quellen versuchen zu extrahieren...

**Comment by Luux** [comment]
Dann würde ich aber vorschlagen, wirklich noch einen Flag in der DB zu setzen, ob der Store-Eintrag zum Crawlzeitpunkt existiert oder nicht.

**Comment by Richie94** [comment]
jo, für games fehlt auch noch das feld für game tags, können wir nachher ja vlt noch angehen...
bin gerade schon halbwegs fleißig...

**Comment by Luux** [comment]
Könnte sich mit #4 erledigen.

**Comment by Luux** [comment]
Ich habe mal einen Workaround für den AgeCheck implementiert, der einen Cookie mit dem Alter benutzt, um sich daran vorbeizuschummeln. Das Regex für die Tags funktioniert allerdings noch nicht richtig.

**Comment by Luux** [comment]
Mach ich auch mal zu.
