### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by Luux** [Richie94/steamRecommend#10]
Ich hab jetzt mal aus Spaß die Erzeugung der "großen" X_game_times-Matrix ganz rausgelassen. Erstaunlicherweise klettert der Speicherverbrauch immer noch auf ~6gb.

Das ganze schwankt jedoch: mal 5.8gb, jetzt grad sogar 6.7gb, ohne das erwähnte Matrix überhaupt genutzt wird.

@Richie94 kannst du das bestätigen, oder hab ich irgendwas übersehen? Hab den aktuellen Code mal gepushed (Achtung, viele Test-Auskommentierungen^^)

**Comment by Luux** [comment]
Nachtrag: Die Dateigröße von X_game_times beträgt bei mir jetzt 1kb, während der RAM-Verbrauch trotzdem auf über 6gb steigt. Da stimmt was nicht... Anscheinend liegt unser Memory-Problem woanders.

**Comment by Richie94** [comment]
Ich versuchs mir morgen mal anzugucken, womit hast du deinen RAM überprüft? Evtl sind unsere Dicts auch noch recht groß oder wir sollten bsp Listen oder die Strings die wir generieren am Ende des Schleifendurchlaufs löschen bzw "freen", der Python Garbage COllector ist nicht wirklich berühmt...

**Comment by Luux** [comment]
Hab mir einfach mit dem Windows Task Manager die RAM-Usage von python.exe angeschaut. 
sys.getsizeof(userGameTimeDict) gibt zudem auch "nur" 786712.
Wir sollten da zwar trotzdem mal einen Blick drauf werfen, allerdings scheint es an irgendwas anderem zu liegen...  (oder sys.getsizeof liefert hier Blödsinn)

**Comment by Richie94** [comment]
http://www.marinamele.com/7-tips-to-time-python-scripts-and-control-memory-and-cpu-usage
