### ISSUE TITLE
Game Crawling

### ISSUE THREAD

**Issue by Luux** [Richie94/steamRecommend#4]
Heyo,

ich hätte da was für's Crawlen der Games gefunden, mit der sich wahrscheinlich das AgeCheck-Problem auch erledigt. 
Mit beispielsweise http://store.steampowered.com/api/appdetails?appids=49520 bekommt man die Daten, die im Store angezeigt werden (neben Namen etc. auch Features wie Controller-Support, die IDs der DLCs, Altersbeschränkung etc.) als JSON.

Sehr interessant ist auch http://api.steampowered.com/ISteamApps/GetAppList/v0001/ welches uns einiges einfacher machen könnte als gedacht.

**Comment by Luux** [comment]
Zu beachten sind, dass nicht alles wirklich "Apps" sind, sondern auch zB viele Trailer darunter zu finden sind, die idR geclustert auftreten (zB ab 80405).

Die können wir erstmal mit sammeln; müssten das aber bei eventuellen Auswertungen später beachten.

**Comment by Richie94** [comment]
Die API bringt nur die festen Storeeigenschaften, dort gibt es keine Nutzer-Tags, bei denen wir ja meinten die wären eine sehr sinnvolle Erweiterung...

**Comment by BackCatalogSmog** [comment]
Games sind doch jetz schon alle in der DB, kann das hier geschlossen werden?

**Comment by Richie94** [comment]
Nein, sind ja unvollständig...

**Comment by Richie94** [comment]
Weiterhin TODO, Erik willst du das übernehmen?
Am besten Proxy vorschalten und dann den Rest in steamDB suchen...

**Comment by Luux** [comment]
Hab gerade bemerkt, dass bei einigen "not found" Games trotzdem Tags hinzugefügt werden. Bei Gelegenheit sollten wir die Tagsuche nochmal überprüfen.

**Comment by Luux** [comment]
Das Crawlen der fehlenden Infos aus SteamDB sollte jetzt funktionieren.

**Comment by Luux** [comment]
Es wird allerdings noch eine Fehlermeldung geworfen, wenn das Ende erreicht ist. Das müsste ich mir morgen oder so nochmal ansehen.

**Comment by Luux** [comment]
Sollte eigentlich erledigt sein?
