### ISSUE TITLE
User Tags

### ISSUE THREAD

**Issue by Luux** [Richie94/steamRecommend#5]
Vielleicht hab ich's auch durch das Verwenden der requests-Lib für die Cookies für #1 irgendwie kaputtgemacht, jedoch funktioniert das Rausfiltern der Infos für die Tags noch nicht richtig. Ich kenne mich mit RegEx leider nicht aus; daher hier mal als Beispiel die relevante Stelle im HTML für die Tags von Borderlands 2:

```
<div class="glance_tags popular_tags" data-appid="49520">
                                                                                        <a href="http://store.steampowered.com/tag/en/FPS/?snr=1_5_9__409" class="app_tag" style="display: none;">
                                                                                                FPS                                                                    </a><a href="http://store.steampowered.com/tag/en/Co-op/?snr=1_5_9__409" class="app_tag" style="display: none;">
                                                                                                Co-op                                                                  </a><a href="http://store.steampowered.com/tag/en/Action/?snr=1_5_9__409" class="app_tag" style="display: none;">
                                                                                                Action                                                                 </a><a href="http://store.steampowered.com/tag/en/RPG/?snr=1_5_9__409" class="app_tag" style="display: none;">
                                                                                                RPG                                                                    </a><a href="http://store.steampowered.com/tag/en/Loot/?snr=1_5_9__409" class="app_tag" style="display: none;">
                                                                                                Loot                                                                   </a><a href="http://store.steampowered.com/tag/en/Shooter/?snr=1_5_9__409" class="app_tag" style="display: none;">
                                                                                                Shooter                                                                </a><a href="http://store.steampowered.com/tag/en/Open%20World/?snr=1_5_9__409" class="app_tag" style="display: none;">
                                                                                                Open World                                                             </a><a href="http://store.steampowered.com/tag/en/Funny/?snr=1_5_9__409" class="app_tag" style="display: none;">
                                                                                                Funny                                                                  </a><a href="http://store.steampowered.com/tag/en/Multiplayer/?snr=1_5_9__409" class="app_tag" style="display: none;">
                                                                                                Multiplayer                                                            </a><a href="http://store.steampowered.com/tag/en/Comedy/?snr=1_5_9__409" class="app_tag" style="display: none;">
                                                                                                Comedy                                                                 </a><a href="http://store.steampowered.com/tag/en/Adventure/?snr=1_5_9__409" class="app_tag" style="display: none;">
                                                                                                Adventure                                                              </a><a href="http://store.steampowered.com/tag/en/Action%20RPG/?snr=1_5_9__409" class="app_tag" style="display: none;">
                                                                                                Action RPG                                                             </a><a href="http://store.steampowered.com/tag/en/Memes/?snr=1_5_9__409" class="app_tag" style="display: none;">
                                                                                                Memes                                                                  </a><a href="http://store.steampowered.com/tag/en/Online%20Co-Op/?snr=1_5_9__409" class="app_tag" style="display: none;">
                                                                                                Online Co-Op                                                           </a><a href="http://store.steampowered.com/tag/en/Stylized/?snr=1_5_9__409" class="app_tag" style="display: none;">
                                                                                                Stylized                                                               </a><a href="http://store.steampowered.com/tag/en/Futuristic/?snr=1_5_9__409" class="app_tag" style="display: none;">
                                                                                                Futuristic                                                             </a><a href="http://store.steampowered.com/tag/en/Sci-fi/?snr=1_5_9__409" class="app_tag" style="display: none;">
                                                                                                Sci-fi                                                                 </a><a href="http://store.steampowered.com/tag/en/Dark%20Humor/?snr=1_5_9__409" class="app_tag" style="display: none;">
                                                                                                Dark Humor                                                             </a><a href="http://store.steampowered.com/tag/en/Singleplayer/?snr=1_5_9__409" class="app_tag" style="display: none;">
                                                                                                Singleplayer                                                           </a><a href="http://store.steampowered.com/tag/en/Atmospheric/?snr=1_5_9__409" class="app_tag" style="display: none;">
                                                                                                Atmospheric                                                            </a><div class="app_tag add_button" onclick="ShowAppTagModal( 49520 )">+</div>
                                                                                </div>
                                                                        </div>

```

<div class="glance_tags popular_tags" data-appid="49520">
                                                                                        <a href="http://store.steampowered.com/tag/en/FPS/?snr=1_5_9__409" class="app_tag" style="display: none;">
                                                                                                FPS                                                                    </a><a href="http://store.steampowered.com/tag/en/Co-op/?snr=1_5_9__409" class="app_tag" style="display: none;">
                                                                                                Co-op                                                                  </a><a href="http://store.steampowered.com/tag/en/Action/?snr=1_5_9__409" class="app_tag" style="display: none;">
                                                                                                Action                                                                 </a><a href="http://store.steampowered.com/tag/en/RPG/?snr=1_5_9__409" class="app_tag" style="display: none;">
                                                                                                RPG                                                                    </a><a href="http://store.steampowered.com/tag/en/Loot/?snr=1_5_9__409" class="app_tag" style="display: none;">
                                                                                                Loot                                                                   </a><a href="http://store.steampowered.com/tag/en/Shooter/?snr=1_5_9__409" class="app_tag" style="display: none;">
                                                                                                Shooter                                                                </a><a href="http://store.steampowered.com/tag/en/Open%20World/?snr=1_5_9__409" class="app_tag" style="display: none;">
                                                                                                Open World                                                             </a><a href="http://store.steampowered.com/tag/en/Funny/?snr=1_5_9__409" class="app_tag" style="display: none;">
                                                                                                Funny                                                                  </a><a href="http://store.steampowered.com/tag/en/Multiplayer/?snr=1_5_9__409" class="app_tag" style="display: none;">
                                                                                                Multiplayer                                                            </a><a href="http://store.steampowered.com/tag/en/Comedy/?snr=1_5_9__409" class="app_tag" style="display: none;">
                                                                                                Comedy                                                                 </a><a href="http://store.steampowered.com/tag/en/Adventure/?snr=1_5_9__409" class="app_tag" style="display: none;">
                                                                                                Adventure                                                              </a><a href="http://store.steampowered.com/tag/en/Action%20RPG/?snr=1_5_9__409" class="app_tag" style="display: none;">
                                                                                                Action RPG                                                             </a><a href="http://store.steampowered.com/tag/en/Memes/?snr=1_5_9__409" class="app_tag" style="display: none;">
                                                                                                Memes                                                                  </a><a href="http://store.steampowered.com/tag/en/Online%20Co-Op/?snr=1_5_9__409" class="app_tag" style="display: none;">
                                                                                                Online Co-Op                                                           </a><a href="http://store.steampowered.com/tag/en/Stylized/?snr=1_5_9__409" class="app_tag" style="display: none;">
                                                                                                Stylized                                                               </a><a href="http://store.steampowered.com/tag/en/Futuristic/?snr=1_5_9__409" class="app_tag" style="display: none;">
                                                                                                Futuristic                                                             </a><a href="http://store.steampowered.com/tag/en/Sci-fi/?snr=1_5_9__409" class="app_tag" style="display: none;">
                                                                                                Sci-fi                                                                 </a><a href="http://store.steampowered.com/tag/en/Dark%20Humor/?snr=1_5_9__409" class="app_tag" style="display: none;">
                                                                                                Dark Humor                                                             </a><a href="http://store.steampowered.com/tag/en/Singleplayer/?snr=1_5_9__409" class="app_tag" style="display: none;">
                                                                                                Singleplayer                                                           </a><a href="http://store.steampowered.com/tag/en/Atmospheric/?snr=1_5_9__409" class="app_tag" style="display: none;">
                                                                                                Atmospheric                                                            </a><div class="app_tag add_button" onclick="ShowAppTagModal( 49520 )">+</div>
                                                                                </div>
                                                                        </div>

Was stattdessen momentan ausgegeben wird:

['FPS', 'Action', 'Loot', 'Open World', 'Multiplayer', 'Adventure', 'Memes', 'Stylized', 'Sci-fi', 'Singleplayer']
['FPS', 'Action', 'Loot', 'Open World', 'Multiplayer', 'Adventure', 'Memes', 'Stylized', 'Sci-fi', 'Singleplayer']

**Comment by Luux** [comment]
Alternativ habe ich noch eine undokumentierte Funktion gefunden:
http://store.steampowered.com/tagdata/recommendedtags?count=49520
(appID bei count angeben)

Hierbei ist zu beachten, dass ein eingeloggter Nutzeraccount benötigt wird, aber vllt. kann man das ja auch noch irgendwie umgehen... Oder vielleicht gibt es noch so eine versteckte Funktion, die ohne eingeloggten Nutzer funktioniert...

**Comment by Richie94** [comment]
Erledigt, fehlte ein re.DOTALL flag beim re.compile, anscheinend wurden manche sachen zu früh oder falsch gematcht...
