### ISSUE TITLE
Call Limit Store

### ISSUE THREAD

**Issue by Richie94** [Richie94/steamRecommend#6]
Bin mir gerade nicht sicher, obs für das Store Crawlen nen Call Limit gibt, weil das ja nicht übern API Key läuft. Hab mir mal sicherheitshalber nen Proxy eingerichtet wie bei http://stackoverflow.com/questions/5620263/using-an-http-proxy-python
Geht von der Zeit her auch recht fix. Wobei wir ja auch nicht allzu viel aus dem Store crawlen müssen bisher...

**Comment by Luux** [comment]
Sollte denke auch auch zugemacht werden können
