### ISSUE TITLE
Gametimes einpflegen

### ISSUE THREAD

**Issue by Richie94** [Richie94/steamRecommend#8]
Da ihr meintet GitHub nutzen, schreib ichs hier:

Ich hab nun ne Methode geschrieben um die GameTimes einzulesen, die userGameTimes enthält nun für jeden User alle entsprechenden Zeiten, das X_game_times ist dann eben das X nur für die game times. Ich hatte es schonmal versucht und es klappte so mäßig, nun das X nach dem Count Vect mit dem neuen X zu verbinden. Kann das vlt von euch noch jmd versuchen? 

Hatte da ne Funktion für geschrieben mit nem Ansatz, aber joa, Aufgabenteilung...
Außerdem bekomme ich wenn ich das nur mit den Zeiten versuche zu kalkulieren einen Memory Error, vlt bekommt ihr das ja auch gefixt...

**Comment by Luux** [comment]
Ich seh mir das demnächst mal an; heute wird's aber nicht mehr ^^

**Comment by Luux** [comment]
Zum Arbeitsspeicher-Problem: bei mir nimmt die aktuelle Version grad zeitweise fast 6-8gb vom RAM; für's Notebook ist das dann wahrscheinlich zu viel. Im Zweifelsfall würde hier Taurus Abhilfe schaffen.
Ansonsten bin ich grad dabei, mich mal durch den Code zu hangeln.
